# Generated by Django 5.1 on 2024-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirickmorty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=90)),
                ('origin', models.URLField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name=models.URLField(verbose_name='300px'))),
                ('episode', models.CharField(max_length=180)),
                ('url', models.URLField(max_length=255)),
                ('create', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
